# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  opctwin:
    image: microsoft/iot-opc-twin-service
    ports:
      - "9042:9042"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL
